export const SERVICEPORTS = {
  GATEWAY: 3000,
  AUTH: 4000,
  GAME: 4001,
  LEAGUE: 4002,
  TEAM: 4003,
  PLAYER: 4004,
  AUCTION: 4005,
  TENANT: 4006,
  BILLING: 4007,
  NOTIFICATION: 4008,
  REALTIME: 4009,
  FIELD: 4010,
  TOURNAMENT: 4011,
  MATCH: 4012,
  STATS: 4013,
  PLATFORM: 4014,
} as const;

export const Services = Object.fromEntries(
  Object.entries(SERVICEPORTS).map(([key, port]) => [
    key,
    `http://localhost:${port}`,
  ]),
) as Record<keyof typeof SERVICEPORTS, string>;

export const SERVICES = {
  GATEWAY_SERVICE: 'GATEWAY_SERVICE',
  AUTH_SERVICE: 'AUTH_SERVICE',
  GAME_SERVICE: 'GAME_SERVICE',
  LEAGUE_SERVICE: 'LEAGUE_SERVICE',
  TEAM_SERVICE: 'TEAM_SERVICE',
  PLAYER_SERVICE: 'PLAYER_SERVICE',
  AUCTION_SERVICE: 'AUCTION_SERVICE',
  TENANT_SERVICE: 'TENANT_SERVICE',
  BILLING_SERVICE: 'BILLING_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  REALTIME_SERVICE: 'REALTIME_SERVICE',
  FIELD_SERVICE: 'FIELD_SERVICE',
  TOURNAMENT_SERVICE: 'TOURNAMENT_SERVICE',
  MATCH_SERVICE: 'MATCH_SERVICE',
  STATS_SERVICE: 'STATS_SERVICE',
  PLATFORM_SERVICE: 'PLATFORM_SERVICE',
} as const;
