export const ServicePorts = {
  GAME: 4001,
  LEAGUE: 4002,
  TEAM: 4003,
  PLAYER: 4004,
  AUCTION: 4005,
  TENANT: 4006,
  BILLING: 4007,
  NOTIFICATION: 4008,
  REALTIME: 4009,
  FIELD: 4010,
  TOURNAMENT: 4011,
  MATCH: 4012,
  STATS: 4013,
  PLATFORM: 4014,
};

export const Services = {
  GAME: `http://localhost:${ServicePorts.GAME}`,
  LEAGUE: `http://localhost:${ServicePorts.LEAGUE}`,
  TEAM: `http://localhost:${ServicePorts.TEAM}`,
  PLAYER: `http://localhost:${ServicePorts.PLAYER}`,
  AUCTION: `http://localhost:${ServicePorts.AUCTION}`,
  TENANT: `http://localhost:${ServicePorts.TENANT}`,
  BILLING: `http://localhost:${ServicePorts.BILLING}`,
  NOTIFICATION: `http://localhost:${ServicePorts.NOTIFICATION}`,
  REALTIME: `http://localhost:${ServicePorts.REALTIME}`,
  FIELD: `http://localhost:${ServicePorts.FIELD}`,
  TOURNAMENT: `http://localhost:${ServicePorts.TOURNAMENT}`,
  MATCH: `http://localhost:${ServicePorts.MATCH}`,
  STATS: `http://localhost:${ServicePorts.STATS}`,
  PLATFORM: `http://localhost:${ServicePorts.PLATFORM}`,
};

export const SERVICES = {
  GAME_SERVICE: 'GAME_SERVICE',
  LEAGUE_SERVICE: 'LEAGUE_SERVICE',
  TEAM_SERVICE: 'TEAM_SERVICE',
  PLAYER_SERVICE: 'PLAYER_SERVICE',
  AUCTION_SERVICE: 'AUCTION_SERVICE',
  TENANT_SERVICE: 'TENANT_SERVICE',
  BILLING_SERVICE: 'BILLING_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  REALTIME_SERVICE: 'REALTIME_SERVICE',
  FIELD_SERVICE: 'FIELD_SERVICE',
  TOURNAMENT_SERVICE: 'TOURNAMENT_SERVICE',
  MATCH_SERVICE: 'MATCH_SERVICE',
  STATS_SERVICE: 'STATS_SERVICE',
  PLATFORM_SERVICE: 'PLATFORM_SERVICE',
};
