export enum SeasonStatus {
  UPCOMING = 'UPCOMING',
  REGISTRATION_OPEN = 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  AUCTION_LIVE = 'AUCTION_LIVE',
  COMPLETED = 'COMPLETED',
}
