version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: service_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: sanjeev
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: service_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sanjeev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - service_network

  redis:
    image: redis:7-alpine
    container_name: service_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - service_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: service_rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - service_network

volumes:
  postgres_data:

networks:
  service_network:
    driver: bridge